### ISSUE TITLE
Format problem with the label file

### ISSUE THREAD

**Issue by yana-xuyan** [gydpku/PPTC#7]
Hi, thank you for your great work!

I just made the dataset following the instructions. However, it seems that the modified text in the resulting label file cannot maintain its original format. For example, in edit template `11_0.pptx` label file, the font style and size turn to `Arial` and `14 pt`, while in the input file, they are `Staatliches` and `65 pt`. Is there anything wrong with this output?

**Comment by gydpku** [comment]
Hi Yana

We have fixed this problem and updated the PPT_executor.py file. You can re-generate the label file now. Sorry for this bug.

**Comment by yana-xuyan** [comment]
#Dialogues: 50
Traceback (most recent call last):
  File "D:\Workspace\Agent\ppt_agent\PPTC\main.py", line 226, in <module>
    prepare_data(ppt_assistant, args)
  File "D:\Workspace\Agent\ppt_agent\PPTC\main.py", line 12, in prepare_data
    ppt_assistant.load_ppt(os.path.join(args.user_path+'long_slides',f'{idx}.pptx'))
  File "D:\Workspace\Agent\ppt_agent\PPTC\src\modeling.py", line 69, in load_ppt
    ppt_executor.set_ppt(path)
  File "D:\Workspace\Agent\ppt_agent\PPTC\src\ppt_executor.py", line 175, in set_ppt
    ppt_reader.set_slides(slides)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'src.ppt_reader' has no attribute 'set_slides'


Hi, I got an error when executing the code for generating the label files.

**Comment by gydpku** [comment]
Hi Yana

We update the ppt_reader file now and test it again.

**Comment by yana-xuyan** [comment]
Hi Yiduo, thank you for your help! However, the error still remains.
```
#Dialogues: 50
Traceback (most recent call last):
  File "D:\Workspace\Agent\ppt_agent\PPTC\main.py", line 227, in <module>
    prepare_data(ppt_assistant, args)
  File "D:\Workspace\Agent\ppt_agent\PPTC\main.py", line 12, in prepare_data        
    ppt_assistant.load_ppt(os.path.join(args.user_path+'long_slides',f'{idx}.pptx'))
  File "D:\Workspace\Agent\ppt_agent\PPTC\src\modeling.py", line 69, in load_ppt    
    ppt_executor.set_ppt(path)
  File "D:\Workspace\Agent\ppt_agent\PPTC\src\ppt_executor.py", line 176, in set_ppt
    ppt_reader.set_slides(slides)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'src.ppt_reader' has no attribute 'set_slides'
```

In the recent commits, seems `ppt_executor` and `ppt_reader` have common functions, but `set_slides` is still not there. I would really appreciate it if you could help further check this issue!

**Comment by gydpku** [comment]
We update it and check the set_slides function now.
